services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-community
    env_file:
      - .env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev